### ISSUE TITLE
example haproxy-api

### ISSUE THREAD

**Issue by glipka** [newrelic/sidecar#23]
hi
Is there an example of using haproxy-api with external haproxy ?
Best regards

**Comment by relistan** [comment]
This shows how to configure it: https://github.com/newrelic/sidecar/blob/master/docker/sidecar.docker.toml#L25

The listeners should contain a URL that will allow Sidecar to connect to `haproxy-api`. You will also need to point `haproxy-api` to where it can fetch an initial Sidecar state like this: https://github.com/Nitro/haproxy-api/blob/master/haproxy-api.toml#L13

If you run all the defaults, these settings should work as-is.

**Comment by glipka** [comment]
thanks for your help
